### ISSUE TITLE
Cross-platform support?

### ISSUE THREAD

**Issue by devblackops** [PoshCode/Configuration#13]
@Jaykul Any there any plans/desire to add cross-platform support to this module?

Skimming through the source, I don't see anything that would prevent this module from working on Linux/MacOS (other than the use of Windows-specific environment variables for where to store the configuration(s).

**Comment by Jaykul** [comment]
You should be able use it by specifying the storage paths on import (as we do in testing), or just setting the environment variables for AppData, LocalAppData, and ProgramData (that is, machine AppData). It's all on [lines 4-7](https://github.com/PoshCode/Configuration/blob/master/Source/Configuration.psm1#L4-L11)

But I'm not sure what paths to use on linux, or how to determine across all the supported distros, so I haven't fixed it yet. Any thoughts?

I'd be willing to loose the separation of "user" vs "user roaming" to support the lowest common denominator if need be, but what paths would need to be used for User-specific vs Machine-wide settings?

**Comment by scrthq** [comment]
for the user profile, you could abstract the environment variable aspect and use `$UserData = (Join-Path "~" "\AppData\Local")`, then create the folder structure if not there (this is what the AWS .NET SDK does for the SDKCredentialStore, albeit clunky and not very OS agnostic feeling)

**Comment by devblackops** [comment]
I don't know if there is really an equivalent for `$env:AppData` in *nix.

I think the logical mapping of `$env:ProgramData` and `$env:LocalAppData` would be:
- $env:LocalAppData -> `~/.<modulefoo>`
- $env:ProgramData -> `/etc/<modulefoo>`

Anyone with more *nix experience feel free to correct me.

**Comment by RamblingCookieMonster** [comment]
Ran into some of this toying with psneo4j xplat.  Another thing to change is [the `mkdir` call](https://github.com/PoshCode/Configuration/blob/master/Source/Configuration.psm1#L136).  IIRC that, along with the overridden paths, got things up and running.

Cheers!

**Comment by Jaykul** [comment]
@RamblingCookieMonster did they remove that function on Linux, or am I missing something?

**Comment by RamblingCookieMonster** [comment]
They do!  just... not with `-Force` - changed it to `New-Item -ItemType Directory...`

**Comment by Jaykul** [comment]
That's ok, I just recently became aware that `-Force` is flawed (if there's _file_ and you're trying to make a folder, it silently does ... nothing). We should make that ... safer.

**Comment by Jaykul** [comment]
Any of you willing to pull my /dev branch, run build, and try it on OS X or Linux? ;)

**Comment by Jaykul** [comment]
OK. Fine. I've got the tests working on Linux and it's ... working. Open new issues if there any problems 😁
