### ISSUE TITLE
Get-Metadata doesnot return arrays

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [PoshCode/Configuration#19]
Version 1.3.1 in the gallery doesnot return properties that are arrays

![image](https://user-images.githubusercontent.com/6729780/43385539-e3e361a8-93d8-11e8-8168-6d6c848423d0.png)

**Comment by Jaykul** [comment]
Ouch. Sorry about that. 
I kept this version in preview for awhile because I was worried about this change, but didn't notice this myself.

I'll write a test to demonstrate, and see if I can figure out a way to solve it without loosing support for PS3. Ugh.

**Comment by Jaykul** [comment]
Finally fixed this today!
