### ISSUE TITLE
Export-Configuration Overwriting Existing Nested Hashtable Values for User

### ISSUE THREAD

**Issue by jkubecki** [PoshCode/Configuration#38]
#### Issue description

When using a nested Hashtable with more than 1 value, using `Export-Configuration` to save the values individually overwrites the previous values for the nested Hashtable.

_Sorry if this format is not good for reporting this bug - tried to be as detailed as possible and provide test/example scenario files._

#### Steps to reproduce the issue

* See the attached **Configuration.psd1.txt** and **Test.ps1.txt** files
  * [Configuration.psd1.txt](https://github.com/PoshCode/Configuration/files/4698424/Configuration.psd1.txt)
  * [Test.ps1.txt](https://github.com/PoshCode/Configuration/files/4698425/Test.ps1.txt)
* Place both in the same folder, removing the .txt extensions
* Execute **Test.ps1**

#### What's the expected result?

The end of the output to show BOTH values having been overridden in User Configuration file, **and** Final Config to reflect BOTH overrides:

```
*** User Configuration File w Foo.Bar AND Foo.Baz overridden

@{
  Foo = @{
    Bar = 42
    Baz = 8675309
  }
}

*** Final Config
{
  "Foo": {
    "Bar": 42,
    "Baz": 8675309
  }
}
```

#### What's the actual result?

The end of the output shows only the MOST RECENT value having been overridden in User Configuration file, **and** Final Config only reflects the MOST RECENT override:

```
*** User Configuration File w Foo.Bar AND Foo.Baz overridden

@{
  Foo = @{
    Baz = 8675309
  }
}

*** Final Config
{
  "Foo": {
    "Bar": 1,
    "Baz": 8675309
  }
}
```

**Comment by Jaykul** [comment]
I'm not sure that I follow what you _expected_ to happen, but perhaps I need to document this better. 

The `Export` command follows PowerShell's _usual_ semantics for export: it takes an input object and exports _that entire object_, overwriting any previous content in the destination. It is not an `Update` and that is why there is an `Update-Metadata` and `Update-Object`.

Essentially, Import-Configuration and Export-Configuration always work with the full Configuration object, and the `Export` command is not designed to allow you to export a subset, nor only the values the user has changed.

If you want to update a single value, you should either:
1. `Import-Metadata` and add or set the value, then `Export-Metadata`
2. Use `Update-Metadata` (note: this currently can't _add_ values)

![WindowsTerminal_2021-01-18_23-38-19](https://user-images.githubusercontent.com/192942/104988517-4af74000-59e6-11eb-80d3-00efeedd3426.png)
