### ISSUE TITLE
Missing signature

### ISSUE THREAD

**Issue by brainz80** [PoshCode/Configuration#45]
When updating I get:

```
The version '1.5.0' of the module 'Configuration' being installed is not catalog signed. Ensure that      
the version '1.5.0' of the module 'Configuration' has the catalog file 'Configuration.cat' and signed     
with the same publisher 'CN=Joel H. Bennett, O=Joel H. Bennett, L=West Henrietta, S=New York, C=US'       
as the previously-installed module 'Configuration' with version '1.3.1' under the directory               
'%userprofile%\Documents\PowerShell\Modules\Configuration\1.3.1'. If you still want to install or        
update, use -SkipPublisherCheck parameter.

**Comment by nstrelow** [comment]
same problem here

**Comment by brainz80** [comment]
Took the risk and updated. To update I had to install the module `Configuration` with:
```posh
Install-Module Configuration -SkipPublisherCheck -Force
```

then remove the previous version:
```posh
$Latest = Get-InstalledModule Configuration
Get-InstalledModule Configuration -AllVersions | Where-Object { $_.Version -ne $Latest.Version } | Uninstall-Module
```

haven't noticed any problems so far. Though hopefully the next updates will fix this issue.

**Comment by Jaykul** [comment]
I am sorry about that. I've let my code-signing certificates lapse.
Frankly, during 2020 the process for renewing them was broken.

I'm not sure if I'll renew them or now. I'm really not convinced anyone cares about code signing of PowerShell modules except when it breaks something like this, so _not_ signing seems like the safer thing.
