### ISSUE TITLE
Are scripts also able to benefit from this configuration module?

### ISSUE THREAD

**Issue by siims-biz** [PoshCode/Configuration#51]
Are powershell scripts also able to benefit from this configuration module?

**Comment by Jaykul** [comment]
Sure thing. 

`Import-ParameterConfiguration` and `Get-ParameterValue` in particular are specifically written for scripts to load default parameter values from a config file.

You can also use `Export-Configuration` and `Import-Configuration` with the ManualOverride parameter set, where you explicitly pass the `-CompanyName` and `-Name` that are used to calculate a path for storage.
