### ISSUE TITLE
Release 1.0.2 not here

### ISSUE THREAD

**Issue by lboening** [PoshCode/Configuration#9]
I see the release 1.0.2 is not available here as it is in PowershellGallery.com. Would you be able to create a release here in Github?

**Comment by Jaykul** [comment]
Yes. I've clearly screwed up commits ... I'll fix this tonight.

Why do you want a *release* on Github?

**Comment by lboening** [comment]
Because I often bypass Chocolatey, Nuget, and PowershellGallery and just get the file from Github releases. This is mostly because of mish-mash of older Windows 7 machines I support.

**Comment by Jaykul** [comment]
Pushed. I'm really not sure how I managed to release 1.0.2 when it should have been 1.0.1 -- but I guess that's the problem with doing releases manually instead of just building it into the automated CI build on Master.
